import { Container } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import BottomNavigationComponent from "../components/bottom-navigation";
import EventListing from "../components/event-listing";
import ResponsiveAppBar from "../components/header";
import Topbar from "../components/topbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Artery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EventListing />
    </div>
  );
}
